version: '2.12'
services:
  app:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    ports:
    - 8000:8000
    volumes:
      - .:/backend
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=""                              
      - POSTGRES_PASSWORD=""
      - POSTGRES_HOST=""
volumes:  
  postgres_data:
  
   
     
     
